version: '3.8'

services:
  postgres:
    image: postgres                # 使用 PostgreSQL 15 镜像
    container_name: postgres_db       # 容器名称
    environment:
      POSTGRES_USER: root             # 设置用户名为 'root'
      POSTGRES_PASSWORD: 123456       # 设置密码为 '123456'
      POSTGRES_DB: demo               # 设置数据库名为 'demo'
    ports:
      - "5433:5432"                   # 将容器的 5432 端口映射到主机的 5433 端口
    volumes:
      - /opt/docker-data/postgresql:/var/lib/postgresql/data  # 数据映射到主机指定路径

volumes:
  postgres_data:

